### ISSUE TITLE
"ffmpeg" has no attribute '_run'

### ISSUE THREAD

**Issue by slyman928** [diracdeltas/spleeter4max#61]
Used to work with python3.7, changed a bunch of my python doing ai things, stopped working. Been trying to get it working again, did all the updated stuff (python3.9, spleeter2.3). Can't get it going. it did one thing yesterday and I had an output but only "other.wav" and then an error, today i'm just getting the ffmpeg error. Error before was permission denied on the file, reinstalled spleeter and ffmpeg and now this. 

![Untitled](https://user-images.githubusercontent.com/82778699/151087702-b8541868-b0fd-4722-914a-e9b61ceff952.png)

**Info:**
 - spleeter-native
 - Windows
 - Ableton 10.1.18
 - Max 8.1.3

**Comment by diracdeltas** [comment]
hmm haven't seen that one. maybe try reinstalling ffmpeg using the instructions in https://github.com/diracdeltas/spleeter4max/wiki/Installing-ffmpeg-on-Windows? if you type `ffmpeg` in the command prompt, what is the output?

**Comment by slyman928** [comment]
ffmpeg worked normally when running in cmd. manually deleted ffmpeg and spleeter + the spleeter.exe script and reinstalled. now this 
![Screenshot 2022-01-25 213508](https://user-images.githubusercontent.com/82778699/151094611-76c5967d-97ae-4dea-8543-b49ec49089d2.png)

stuck at that

**Comment by diracdeltas** [comment]
it does look like the vocals.wav file was written successfully (does it actually exist) but ran out of memory?

**Comment by slyman928** [comment]
it existed. but just restarted and it all worked successfully. strange that i was getting that ffmpeg error, but yea, seems good. thanks for the help regardless.

**Comment by slyman928** [comment]
it existed. just restarted though and now it's done the bass and vocals and hangs here
![Screenshot 2022-01-25 220303](https://user-images.githubusercontent.com/82778699/151097097-c8fbe9b5-447f-475d-a21a-68ff44d7ed48.png)

this is what it was doing yesterday before i was getting the ffmpeg error. strange i was getting that in the first place but yea...

just tried running again and got the memory error. was having that issue with some ai stuff a while ago, not sure how i remedied it, some sort of memory clear line. i have 32gb ram on this machine though...

**Comment by diracdeltas** [comment]
32gb ram should be plenty. i wonder if just splitting the audio files in half or something will make the error occur less.

**Comment by slyman928** [comment]
that worked, figuring just since it was a wav file, and the original i tried recently was a flac. 128kbps mp3 worked fine 

thanks for the help
